package com.sap.coe.sf;

import javax.xml.ws.WebFault;



/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebFault(	name = "SFWebServiceFault",
			targetNamespace = "urn:fault.sfapi.successfactors.com")
public class SFWebServiceFaultException_Exception extends Exception
{
	private static final long serialVersionUID = 1L;
	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private SFWebServiceFaultException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public SFWebServiceFaultException_Exception(String message,
			SFWebServiceFaultException faultInfo)
	{
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public SFWebServiceFaultException_Exception(String message,
			SFWebServiceFaultException faultInfo, Throwable cause)
	{
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: com.sap.coe.sf.SFWebServiceFaultException
	 */
	public SFWebServiceFaultException getFaultInfo()
	{
		return faultInfo;
	}

	/* (non-Javadoc)
	 * @see java.lang.Throwable#getMessage()
	 */
    @Override
    public String getMessage() {
	    String message = super.getMessage();

	    if (faultInfo != null) {
	    	message += " caused by: " + faultInfo.getErrorMessage() + " - code: " + faultInfo.getErrorCode();
	    }
	    return message;
    }
	
}
